all: q1_expand_list q2_join q3_inside_out q4_toString q5_slice q6_substring

q1_expand_list: q1_expand_list.c
	gcc -std=c11 -g -Wall -o $@ $^

q2_join: q2_join.c
	gcc -std=c11 -g -Wall -o $@ $^

q3_inside_out: q3_inside_out.c
	gcc -std=c11 -g -Wall -o $@ $^

q4_toString: q4_toString.c
	gcc -std=c11 -g -Wall -o $@ $^

q5_slice: q5_slice.c
	gcc -std=c11 -g -Wall -o $@ $^

q6_substring: q6_substring.c
	gcc -std=c11 -g -Wall -o $@ $^	

clean:
	rm -f q1_expand_list q2_join q3_inside_out q4_toString q5_slice q6_substring
